export type PrimaryAttr = 'strength' | 'agility' | 'intelligence' | 'universal'

/**
 * Maps internal hero name → primary attribute.
 * Source: Dota 2 wiki / in-game data.
 */
export const HERO_ATTR: Record<string, PrimaryAttr> = {
  abaddon:              'universal',
  abyssal_underlord:    'strength',
  alchemist:            'strength',
  ancient_apparition:   'intelligence',
  antimage:             'agility',
  arc_warden:           'universal',
  axe:                  'strength',
  bane:                 'universal',
  batrider:             'universal',
  beastmaster:          'universal',
  bloodseeker:          'agility',
  bounty_hunter:        'agility',
  brewmaster:           'universal',
  bristleback:          'strength',
  broodmother:          'agility',
  centaur:              'strength',
  chaos_knight:         'strength',
  chen:                 'intelligence',
  clinkz:               'agility',
  crystal_maiden:       'intelligence',
  dark_seer:            'intelligence',
  dark_willow:          'intelligence',
  dawnbreaker:          'strength',
  dazzle:               'universal',
  death_prophet:        'universal',
  disruptor:            'intelligence',
  doom_bringer:         'strength',
  dragon_knight:        'strength',
  drow_ranger:          'agility',
  earth_spirit:         'strength',
  earthshaker:          'strength',
  elder_titan:          'strength',
  ember_spirit:         'agility',
  enchantress:          'intelligence',
  enigma:               'universal',
  faceless_void:        'agility',
  furion:               'universal',
  grimstroke:           'intelligence',
  gyrocopter:           'agility',
  hoodwink:             'agility',
  huskar:               'strength',
  invoker:              'intelligence',
  jakiro:               'intelligence',
  juggernaut:           'agility',
  keeper_of_the_light:  'intelligence',
  kez:                  'agility',
  kunkka:               'strength',
  largo:                'strength',
  legion_commander:     'strength',
  leshrac:              'intelligence',
  lich:                 'intelligence',
  life_stealer:         'strength',
  lina:                 'intelligence',
  lion:                 'intelligence',
  lone_druid:           'agility',
  luna:                 'agility',
  lycan:                'strength',
  magnataur:            'universal',
  marci:                'universal',
  mars:                 'strength',
  medusa:               'agility',
  meepo:                'agility',
  mirana:               'agility',
  monkey_king:          'agility',
  morphling:            'agility',
  muerta:               'intelligence',
  naga_siren:           'agility',
  necrolyte:            'intelligence',
  nevermore:            'agility',
  night_stalker:        'strength',
  nyx_assassin:         'universal',
  obsidian_destroyer:   'intelligence',
  ogre_magi:            'strength',
  omniknight:           'strength',
  oracle:               'intelligence',
  pangolier:            'universal',
  phantom_assassin:     'agility',
  phantom_lancer:       'agility',
  phoenix:              'strength',
  primal_beast:         'strength',
  puck:                 'intelligence',
  pudge:                'strength',
  pugna:                'intelligence',
  queenofpain:          'intelligence',
  rattletrap:           'strength',
  razor:                'agility',
  riki:                 'agility',
  ringmaster:           'intelligence',
  rubick:               'intelligence',
  sand_king:            'universal',
  shadow_demon:         'intelligence',
  shadow_shaman:        'intelligence',
  shredder:             'strength',
  silencer:             'intelligence',
  skeleton_king:        'strength',
  skywrath_mage:        'intelligence',
  slardar:              'strength',
  slark:                'agility',
  snapfire:             'universal',
  sniper:               'agility',
  spectre:              'agility',
  spirit_breaker:       'strength',
  storm_spirit:         'intelligence',
  sven:                 'strength',
  techies:              'universal',
  templar_assassin:     'agility',
  terrorblade:          'agility',
  tidehunter:           'strength',
  tinker:               'intelligence',
  tiny:                 'strength',
  treant:               'strength',
  troll_warlord:        'agility',
  tusk:                 'strength',
  undying:              'strength',
  ursa:                 'agility',
  vengefulspirit:       'agility',
  venomancer:           'universal',
  viper:                'agility',
  visage:               'universal',
  void_spirit:          'universal',
  warlock:              'intelligence',
  weaver:               'agility',
  windrunner:           'universal',
  winter_wyvern:        'intelligence',
  wisp:                 'universal',
  witch_doctor:         'intelligence',
  zuus:                 'intelligence',
}

export const ATTR_LABEL: Record<PrimaryAttr, string> = {
  strength:     'Strength',
  agility:      'Agility',
  intelligence: 'Intelligence',
  universal:    'Universal',
}

/** Official Dota 2 attribute icons from Steam CDN */
export const ATTR_ICON: Record<PrimaryAttr, string> = {
  strength:     'https://cdn.steamstatic.com/apps/dota2/images/dota_react/icons/hero_strength.png',
  agility:      'https://cdn.steamstatic.com/apps/dota2/images/dota_react/icons/hero_agility.png',
  intelligence: 'https://cdn.steamstatic.com/apps/dota2/images/dota_react/icons/hero_intelligence.png',
  universal:    'https://cdn.steamstatic.com/apps/dota2/images/dota_react/icons/hero_universal.png',
}

export const ATTR_COLOR: Record<PrimaryAttr, string> = {
  strength:     '#f87171',   // red
  agility:      '#4ade80',   // green
  intelligence: '#60a5fa',   // blue
  universal:    '#c084fc',   // purple
}
